driver:
  name: hyperv
  parent_vhd_folder: C:\src\hyperv\WIN2012r2WMF5
  parent_vhd_name: WIN2012r2_WMF5.vhd
  boot_iso_path: C:\src\kitchens\TestScript\Unattendxml.iso
  #iso_path: C:\src\kitchens\TestScript\other.iso
  memory_startup_bytes: 1073741824
  vm_switch: NAT
  ip_address: 10.111.111.161
  subnet: 255.255.255.0
  gateway: 10.111.111.1
  dns_servers: ['8.8.8.8']
  enable_guest_services: true
transport:
  name: winrm
  username: Administrator
  password: <%= ENV['vmpassword'] %>driver:
  name: hyperv
  parent_vhd_folder: C:\src\hyperv\WIN2012r2WMF5
  parent_vhd_name: WIN2012r2_WMF5.vhd
  boot_iso_path: C:\src\kitchens\TestScript\Unattendxml.iso
  #iso_path: C:\src\kitchens\TestScript\other.iso
  memory_startup_bytes: 1073741824
  vm_switch: NAT
  ip_address: 10.111.111.161
  subnet: 255.255.255.0
  gateway: 10.111.111.1
  dns_servers: ['8.8.8.8']
  enable_guest_services: true
transport:
  name: winrm
  username: Administrator
  password: P@ssw0rd

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      configuration_mode_frequency_mins: 15
      debug_mode: none
    configuration_script_folder: ./DSC_Script
    configuration_script: Test-Kitchen-build.ps1
    #modules_path: .
    #retry_on_exit_code:
    #- 35
    #- 1
    configuration_data_variable: ConfigurationData
    modules_from_gallery:
     - ProtectedData
     - Pester
     - xDscResourceDesigner

verifier:
  name: pester
  test_folder: ./Dsc_Validation/

platforms:
  - name: win2012r2
    os_type: windows
    shell: powershell

suites:
  - name: DSCPULLSRV
    driver:
      ip_address: 10.111.111.161
driver:
  name: hyperv
  parent_vhd_folder: C:\src\hyperv\WIN2012r2WMF5
  parent_vhd_name: WIN2012r2_WMF5.vhd
  boot_iso_path: C:\src\kitchens\TestScript\Unattendxml.iso
  #iso_path: C:\src\kitchens\TestScript\other.iso
  memory_startup_bytes: 1073741824
  vm_switch: NAT
  ip_address: 10.111.111.161
  subnet: 255.255.255.0
  gateway: 10.111.111.1
  dns_servers: ['8.8.8.8']
  enable_guest_services: true
transport:
  name: winrm
  username: Administrator
  password: P@ssw0rd

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      configuration_mode_frequency_mins: 15
      debug_mode: none
    configuration_script_folder: ./DSC_Script
    configuration_script: Test-Kitchen-build.ps1
    #modules_path: .
    #retry_on_exit_code:
    #- 35
    #- 1
    configuration_data_variable: ConfigurationData
    modules_from_gallery:
     - ProtectedData
     - Pester
     - xDscResourceDesigner

verifier:
  name: pester
  test_folder: ./Dsc_Validation/

platforms:
  - name: win2012r2
    os_type: windows
    shell: powershell

suites:
  - name: DSCPULLSRV
    driver:
      ip_address: 10.111.111.161
driver:
  name: hyperv
  parent_vhd_folder: C:\src\hyperv\WIN2012r2WMF5
  parent_vhd_name: WIN2012r2_WMF5.vhd
  boot_iso_path: C:\src\kitchens\TestScript\Unattendxml.iso
  #iso_path: C:\src\kitchens\TestScript\other.iso
  memory_startup_bytes: 1073741824
  vm_switch: NAT
  ip_address: 10.111.111.161
  subnet: 255.255.255.0
  gateway: 10.111.111.1
  dns_servers: ['8.8.8.8']
  enable_guest_services: true
transport:
  name: winrm
  username: Administrator
  password: P@ssw0rd

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      configuration_mode_frequency_mins: 15
      debug_mode: none
    configuration_script_folder: ./DSC_Script
    configuration_script: Test-Kitchen-build.ps1
    #modules_path: .
    #retry_on_exit_code:
    #- 35
    #- 1
    configuration_data_variable: ConfigurationData
    modules_from_gallery:
     - ProtectedData
     - Pester
     - xDscResourceDesigner

verifier:
  name: pester
  test_folder: ./Dsc_Validation/

platforms:
  - name: win2012r2
    os_type: windows
    shell: powershell

suites:
  - name: DSCPULLSRV
    driver:
      ip_address: 10.111.111.161
driver:
  name: hyperv
  parent_vhd_folder: C:\src\hyperv\WIN2012r2WMF5
  parent_vhd_name: WIN2012r2_WMF5.vhd
  boot_iso_path: C:\src\kitchens\TestScript\Unattendxml.iso
  #iso_path: C:\src\kitchens\TestScript\other.iso
  memory_startup_bytes: 1073741824
  vm_switch: NAT
  ip_address: 10.111.111.161
  subnet: 255.255.255.0
  gateway: 10.111.111.1
  dns_servers: ['8.8.8.8']
  enable_guest_services: true
transport:
  name: winrm
  username: Administrator
  password: P@ssw0rd

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      configuration_mode_frequency_mins: 15
      debug_mode: none
    configuration_script_folder: ./DSC_Script
    configuration_script: Test-Kitchen-build.ps1
    #modules_path: .
    #retry_on_exit_code:
    #- 35
    #- 1
    configuration_data_variable: ConfigurationData
    modules_from_gallery:
     - ProtectedData
     - Pester
     - xDscResourceDesigner

verifier:
  name: pester
  test_folder: ./Dsc_Validation/

platforms:
  - name: win2012r2
    os_type: windows
    shell: powershell

suites:
  - name: DSCPULLSRV
    driver:
      ip_address: 10.111.111.161
driver:
  name: hyperv
  parent_vhd_folder: C:\src\hyperv\WIN2012r2WMF5
  parent_vhd_name: WIN2012r2_WMF5.vhd
  boot_iso_path: C:\src\kitchens\TestScript\Unattendxml.iso
  #iso_path: C:\src\kitchens\TestScript\other.iso
  memory_startup_bytes: 1073741824
  vm_switch: NAT
  ip_address: 10.111.111.161
  subnet: 255.255.255.0
  gateway: 10.111.111.1
  dns_servers: ['8.8.8.8']
  enable_guest_services: true
transport:
  name: winrm
  username: Administrator
  password: P@ssw0rd

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      configuration_mode_frequency_mins: 15
      debug_mode: none
    configuration_script_folder: ./DSC_Script
    configuration_script: Test-Kitchen-build.ps1
    #modules_path: .
    #retry_on_exit_code:
    #- 35
    #- 1
    configuration_data_variable: ConfigurationData
    modules_from_gallery:
     - ProtectedData
     - Pester
     - xDscResourceDesigner

verifier:
  name: pester
  test_folder: ./Dsc_Validation/

platforms:
  - name: win2012r2
    os_type: windows
    shell: powershell

suites:
  - name: DSCPULLSRV
    driver:
      ip_address: 10.111.111.161


provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      configuration_mode_frequency_mins: 15
      debug_mode: none
    configuration_script_folder: ./DSC_Script
    configuration_script: Test-Kitchen-build.ps1
    #modules_path: .
    #retry_on_exit_code:
    #- 35
    #- 1
    configuration_data_variable: ConfigurationData
    modules_from_gallery:
     - ProtectedData
     - Pester
     - xDscResourceDesigner

verifier:
  name: pester
  test_folder: ./Dsc_Validation/

platforms:
  - name: win2012r2
    os_type: windows
    shell: powershell

suites:
  - name: DSCPULLSRV
    driver:
      ip_address: 10.111.111.161
